name: date_countdown_fschmatz
description: Days counter to an specified date
publish_to: 'none'
version: 2.3.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  easy_dynamic_theme: ^2.3.1
  cupertino_icons: ^1.0.2
  dynamic_system_colors: ^1.8.0
  jiffy: ^6.3.1
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.12
  async_redux: ^25.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/