name: date_countdown_fschmatz
description: Days counter to an specified date
publish_to: 'none'
version: 2.1.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path_provider:
  shared_preferences:
  provider:
  url_launcher:
  intl:
  easy_dynamic_theme:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.7.0
  jiffy: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/